### ISSUE TITLE
[BUG] pd.read_csv() parameter addition

### ISSUE THREAD

**Issue by DaceT** [rapidsai-community/notebooks-contrib#340]
**Describe the bug**
If the file is unreasonably large, the function will only read the first 1 billion rows, according to the instructions for  [07_Introduction_to_XGBoost.ipynb](https://github.com/rapidsai-community/notebooks-contrib/blob/main/getting_started_materials/intro_tutorials_and_guides/07_Introduction_to_XGBoost.ipynb) notebook. The code, however, is missing the section where it does exactly that.

**Steps/Code to reproduce bug**
The line below needs `nrows=1e9` added to the read.csv function in the section beneath the category General Data and subcategory Load Data.

`df = pd.read_csv(filename)` => `df = pd.read_csv(filename, nrows=1e9)` 

**Expected behavior**
Because no error occurred, the expected behavior will remain unchanged. However, only 1e9 rows from the csv file will be read.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of RAPIDS libraries install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
   - If other methods, provide the commands used
 

**Additional context**

**Comment by taureandyernv** [comment]
closed with #341
