### ISSUE TITLE
[QST] Error Running RAPIDS using Docker on Mac and Windows

### ISSUE THREAD

**Issue by chetkar** [rapidsai-community/notebooks-contrib#363]
**What is your question?**
Hi,
While running the RAPIDS using Docker on both Mac and Windows. I am getting the following error.

"
System has not been booted with system as init system (PID 1). Can't operate.
Failed to create bus connection: Host is down
"

Best,
Chetkar

**Comment by beckernick** [comment]
This error suggests the issue is likely unrelated to RAPIDS. Are you able to use other Docker containers on your system?

Please note that RAPIDS is not supported on Macs and only [WSL2 on Windows 11](https://rapids.ai/wsl2.html) is officially supported for Windows.
